# Generated by Django 3.2.6 on 2021-08-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_video_video_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='Video_image',
            new_name='video_image',
        ),
    ]
