# Generated by Django 3.2.6 on 2021-08-29 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_rename_video_image_video_video_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_image',
            field=models.ImageField(upload_to='video'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pro', models.BooleanField(default=False)),
                ('pro_expiery_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_type', models.CharField(choices=[('F', 'FRESS'), ('M', 'MONTHLY'), ('Y', 'YEARLY')], default='FREE', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
