# Generated by Django 3.2.6 on 2021-09-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210907_2225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_pro',
        ),
    ]
