# Generated by Django 3.2.6 on 2021-09-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_profile_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_name',
        ),
    ]
