# Generated by Django 3.2.6 on 2021-09-21 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_contact_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoModule',
        ),
    ]
